name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
        unzip gradle-7.5-bin.zip
        export GRADLE_HOME=$PWD/gradle-7.5
        export PATH=$PATH:$GRADLE_HOME/bin

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
